name: Testing

on:
    push:
    pull_request:

jobs:
    code-style:
        name: Check code style
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "8.1"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Check style on sources
                run: ./bin/phpcs --standard=src/PhpCs/FiveLab/ruleset.xml src/

            -   name: Check style on tests
                run: ./bin/phpcs --standard=tests/phpcs.xml tests/

    php-stan:
        name: Run PHP-Stan
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "8.1"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Run php stan
                run: bin/phpstan

    tests:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [ '7.4', '8.0', '8.1' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: Install stable vendors
                run: composer install --prefer-dist

            -   name: Run tests
                run: bin/phpunit